import { createConfig } from '@gluestack-style/react';
import { config as defaultConfig } from '@gluestack-ui/config';
import { darkTheme, colors } from '@somni/theme';

// Extend the default config with our custom dark theme
export const customConfig = createConfig({
  ...defaultConfig,
  tokens: {
    ...defaultConfig.tokens,
    colors: {
      ...defaultConfig.tokens.colors,
      // Map our theme colors to gluestack tokens
      primary0: colors.white,
      primary50: colors.purple[50],
      primary100: colors.purple[100],
      primary200: colors.purple[200],
      primary300: colors.purple[300],
      primary400: colors.purple[400],
      primary500: darkTheme.colors.primary,
      primary600: colors.purple[600],
      primary700: colors.purple[700],
      primary800: colors.purple[800],
      primary900: colors.purple[900],
      
      // Secondary colors
      secondary0: colors.white,
      secondary50: colors.green[50],
      secondary100: colors.green[100],
      secondary200: colors.green[200],
      secondary300: colors.green[300],
      secondary400: colors.green[400],
      secondary500: darkTheme.colors.secondary,
      secondary600: colors.green[600],
      secondary700: colors.green[700],
      secondary800: colors.green[800],
      secondary900: colors.green[900],
      
      // Text colors - using dark theme values
      textLight0: darkTheme.colors.text.primary,
      textLight50: darkTheme.colors.text.primary,
      textLight100: darkTheme.colors.text.primary,
      textLight200: darkTheme.colors.text.primary,
      textLight300: darkTheme.colors.text.secondary,
      textLight400: darkTheme.colors.text.secondary,
      textLight500: darkTheme.colors.text.secondary,
      textLight600: darkTheme.colors.text.disabled,
      textLight700: darkTheme.colors.text.disabled,
      textLight800: darkTheme.colors.text.disabled,
      textLight900: darkTheme.colors.text.disabled,
      textLight950: darkTheme.colors.text.disabled,
      
      textDark0: darkTheme.colors.text.inverse,
      textDark50: darkTheme.colors.text.inverse,
      textDark100: darkTheme.colors.text.inverse,
      textDark200: darkTheme.colors.text.inverse,
      textDark300: darkTheme.colors.text.disabled,
      textDark400: darkTheme.colors.text.disabled,
      textDark500: darkTheme.colors.text.disabled,
      textDark600: darkTheme.colors.text.secondary,
      textDark700: darkTheme.colors.text.secondary,
      textDark800: darkTheme.colors.text.secondary,
      textDark900: darkTheme.colors.text.primary,
      textDark950: darkTheme.colors.text.primary,
      
      // Background colors - using dark theme values
      backgroundLight0: darkTheme.colors.background.primary,
      backgroundLight50: darkTheme.colors.background.secondary,
      backgroundLight100: darkTheme.colors.background.elevated,
      backgroundLight200: darkTheme.colors.background.elevated,
      backgroundLight300: colors.gray[800],
      backgroundLight400: colors.gray[700],
      backgroundLight500: colors.gray[600],
      backgroundLight600: colors.gray[500],
      backgroundLight700: colors.gray[400],
      backgroundLight800: colors.gray[300],
      backgroundLight900: colors.gray[200],
      backgroundLight950: colors.gray[900],
      
      backgroundDark0: colors.white,
      backgroundDark50: colors.gray[50],
      backgroundDark100: colors.gray[100],
      backgroundDark200: colors.gray[200],
      backgroundDark300: colors.gray[300],
      backgroundDark400: colors.gray[400],
      backgroundDark500: colors.gray[500],
      backgroundDark600: colors.gray[600],
      backgroundDark700: colors.gray[700],
      backgroundDark800: darkTheme.colors.background.elevated,
      backgroundDark900: darkTheme.colors.background.secondary,
      backgroundDark950: darkTheme.colors.background.primary,
      
      // Border colors - using dark theme values
      borderLight0: darkTheme.colors.border.primary,
      borderLight50: darkTheme.colors.border.primary,
      borderLight100: darkTheme.colors.border.primary,
      borderLight200: darkTheme.colors.border.primary,
      borderLight300: darkTheme.colors.border.secondary,
      borderLight400: darkTheme.colors.border.secondary,
      borderLight500: colors.gray[500],
      borderLight600: colors.gray[400],
      borderLight700: colors.gray[300],
      borderLight800: colors.gray[200],
      borderLight900: colors.gray[100],
      borderLight950: colors.gray[50],
      
      borderDark0: colors.white,
      borderDark50: colors.gray[50],
      borderDark100: colors.gray[100],
      borderDark200: colors.gray[200],
      borderDark300: colors.gray[300],
      borderDark400: colors.gray[400],
      borderDark500: colors.gray[500],
      borderDark600: colors.gray[600],
      borderDark700: darkTheme.colors.border.secondary,
      borderDark800: darkTheme.colors.border.primary,
      borderDark900: darkTheme.colors.border.primary,
      borderDark950: darkTheme.colors.border.primary,
      
      // Status colors
      error0: colors.white,
      error50: colors.red[50],
      error100: colors.red[100],
      error200: colors.red[200],
      error300: colors.red[300],
      error400: colors.red[400],
      error500: darkTheme.colors.status.error,
      error600: colors.red[600],
      error700: colors.red[700],
      error800: colors.red[800],
      error900: colors.red[900],
      error950: colors.red[900],
      
      success0: colors.white,
      success50: colors.green[50],
      success100: colors.green[100],
      success200: colors.green[200],
      success300: colors.green[300],
      success400: colors.green[400],
      success500: darkTheme.colors.status.success,
      success600: colors.green[600],
      success700: colors.green[700],
      success800: colors.green[800],
      success900: colors.green[900],
      success950: colors.green[900],
      
      warning0: colors.white,
      warning50: colors.yellow[50],
      warning100: colors.yellow[100],
      warning200: colors.yellow[200],
      warning300: colors.yellow[300],
      warning400: colors.yellow[400],
      warning500: darkTheme.colors.status.warning,
      warning600: colors.yellow[600],
      warning700: colors.yellow[700],
      warning800: colors.yellow[800],
      warning900: colors.yellow[900],
      warning950: colors.yellow[900],
      
      info0: colors.white,
      info50: colors.blue[50],
      info100: colors.blue[100],
      info200: colors.blue[200],
      info300: colors.blue[300],
      info400: colors.blue[400],
      info500: darkTheme.colors.status.info,
      info600: colors.blue[600],
      info700: colors.blue[700],
      info800: colors.blue[800],
      info900: colors.blue[900],
      info950: colors.blue[900],
    },
    space: {
      ...defaultConfig.tokens.space,
      '0': 0,
      '0.5': darkTheme.spacing.xs / 2,
      '1': darkTheme.spacing.xs,
      '1.5': darkTheme.spacing.xs * 1.5,
      '2': darkTheme.spacing.small,
      '2.5': darkTheme.spacing.small * 1.25,
      '3': darkTheme.spacing.medium * 0.75,
      '3.5': darkTheme.spacing.medium * 0.875,
      '4': darkTheme.spacing.medium,
      '5': darkTheme.spacing.medium * 1.25,
      '6': darkTheme.spacing.large,
      '7': darkTheme.spacing.large * 1.166,
      '8': darkTheme.spacing.xl,
      '9': darkTheme.spacing.xl * 1.125,
      '10': darkTheme.spacing.xl * 1.25,
      '12': darkTheme.spacing.xxl,
      '16': darkTheme.spacing.xxl * 1.333,
      '20': darkTheme.spacing.xxl * 1.666,
      '24': darkTheme.spacing.xxl * 2,
    },
    radii: {
      ...defaultConfig.tokens.radii,
      'none': 0,
      'xs': darkTheme.borderRadius.small / 2,
      'sm': darkTheme.borderRadius.small,
      'md': darkTheme.borderRadius.medium,
      'lg': darkTheme.borderRadius.large,
      'xl': darkTheme.borderRadius.large * 1.5,
      '2xl': darkTheme.borderRadius.large * 2,
      '3xl': darkTheme.borderRadius.large * 2.5,
      'full': darkTheme.borderRadius.round,
    },
    fontSizes: {
      ...defaultConfig.tokens.fontSizes,
      '2xs': darkTheme.typography.caption.fontSize * 0.75,
      'xs': darkTheme.typography.caption.fontSize * 0.875,
      'sm': darkTheme.typography.caption.fontSize,
      'md': darkTheme.typography.body.fontSize,
      'lg': darkTheme.typography.body.fontSize * 1.125,
      'xl': darkTheme.typography.h3.fontSize,
      '2xl': darkTheme.typography.h2.fontSize,
      '3xl': darkTheme.typography.h1.fontSize,
      '4xl': darkTheme.typography.h1.fontSize * 1.25,
      '5xl': darkTheme.typography.h1.fontSize * 1.5,
      '6xl': darkTheme.typography.h1.fontSize * 1.875,
    },
  },
  components: {
    ...defaultConfig.components,
    Button: {
      ...defaultConfig.components.Button,
      theme: {
        ...defaultConfig.components.Button.theme,
        _web: {
          ':hover': {
            opacity: 0.9,
          },
        },
        ':active': {
          opacity: 0.8,
        },
      },
    },
  },
});