#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running linter before commit..."
npm run lint --workspaces -- --fix

# Check the exit code of the lint command.
# If it's non-zero, the commit will be aborted.
if [ $? -ne 0 ]; then
  echo "Linting failed. Please fix the errors before committing."
  exit 1
fi

# Stage the files that were automatically fixed by the linter
git add .
